### ISSUE TITLE
Publish npm package

### ISSUE THREAD

**Issue by sebastianconcept** [ympbyc/LittleSmallscript#36]
Hi @ympbyc great work with LittleSmallscript.

Would be great to have it published as an `npm` package because makes easier for other projects to automate embracing it. Example: there is a coffeescript package for Meteor which makes coding Meteor apps very nice indeed, wouldn't be great to have one to code with Smalltalk syntax. What do you think?

**Comment by ympbyc** [comment]
Hi! Sorry for a terribly late reply. I haven't been active on github lately.
That's a good idea. I'll do that sometime soon. Thanks for the suggestion!

**Comment by sebastianconcept** [comment]
Glad to hear back from you @ympbyc thanks! Looking forward to it

**Comment by ympbyc** [comment]
Turns out, I have published a npm package long time ago: https://www.npmjs.com/package/littlesmallscript .
Even I forgot about this.  I updated the README.
